ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
obj-$(CONFIG_MTK_TPD_MMI) := mtk_tpd_mmi.o
mtk_tpd_mmi-objs += mtk_tpd.o
mtk_tpd_mmi-objs += tpd_button.o
mtk_tpd_mmi-objs += tpd_calibrate.o
mtk_tpd_mmi-objs += tpd_default.o
mtk_tpd_mmi-objs += tpd_misc.o
mtk_tpd_mmi-objs += tpd_setting.o
