ccflags-y += -DCONFIG_ABOV_MTK_CHARGER
ccflags-y += -DCONFIG_ABOV_MTK_KERNEL419_CHARGER_TYPE
ccflags-y += -I$(srctree)/$(src)/../../../drivers/base
obj-$(CONFIG_ABOV_SAR_MMI_OVERLAY_7CH) += abov_sar_mmi_overlay_7ch.o
